name: "Github Environment Variables"
on:
  workflow_dispatch:

jobs:
  get-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get environment variables
        uses: Sonu-001/Repo1/github-env@feature/update
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          repo: "procter-gamble/mw-mt-always-en-gb"
          envs: "mw-mt-always-en-gb-development,mw-mt-always-en-gb-staging"

      - name: Upload environment variables
        uses: actions/upload-artifact@v4
        with:
            name: env_var
            path: env_var.json    